[package]
name = "vg_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
chrono = "0.4.24"
convert_case = "0.6.0"
quote = "1.0.26"
rand = "0.8.5"
syn = "2.0.15"
